name: Deploy to S3

on:
  push:
    branches:
      - xyz  # your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # or your preferred region
      
      - name: Deploy to S3
        run: |
          aws s3 sync ./ s3://S3_BUCKEET-NAME/ --delete --exclude ".git/*" --exclude ".github/*"
          
      # Optional: Invalidate CloudFront cache if you're using CloudFront
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"